// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ResolveInside(root: string, fragment: string): $CancellablePromise<string> {
    return $Call.ByID(765230928, root, fragment);
}

export function Summary(root: string): $CancellablePromise<$models.WorkspaceSummary> {
    return $Call.ByID(3245301936, root).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Validate(root: string): $CancellablePromise<$models.ValidationResult> {
    return $Call.ByID(1383094894, root).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.WorkspaceSummary.createFrom;
const $$createType1 = $models.ValidationResult.createFrom;
