// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ImportResult {
    "source": string;
    "destination": string;
    "relativePath": string;
    "bytes": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}
