// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "./session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaceid$0 from "./workspaceid/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class AIProfileDTO {
    "schemaVersion": number;
    "id": string;
    "role": string;
    "kind": string;
    "label": string;
    "model": string;
    "baseUrl": string;
    "credentialRef"?: string;
    "timeoutMs": number;
    "maxInputChars": number;
    "maxHistoryChars": number;
    "maxEvidenceChars": number;
    "maxOutputTokens": number;
    "dimensions"?: number;

    /** Creates a new AIProfileDTO instance. */
    constructor($$source: Partial<AIProfileDTO> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("timeoutMs" in $$source)) {
            this["timeoutMs"] = 0;
        }
        if (!("maxInputChars" in $$source)) {
            this["maxInputChars"] = 0;
        }
        if (!("maxHistoryChars" in $$source)) {
            this["maxHistoryChars"] = 0;
        }
        if (!("maxEvidenceChars" in $$source)) {
            this["maxEvidenceChars"] = 0;
        }
        if (!("maxOutputTokens" in $$source)) {
            this["maxOutputTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProfileDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProfileDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIProfileDTO($$parsedSource as Partial<AIProfileDTO>);
    }
}

export class AIProfilesDTO {
    "chat"?: AIProfileDTO | null;
    "embedding"?: AIProfileDTO | null;

    /** Creates a new AIProfilesDTO instance. */
    constructor($$source: Partial<AIProfilesDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProfilesDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProfilesDTO {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chat" in $$parsedSource) {
            $$parsedSource["chat"] = $$createField0_0($$parsedSource["chat"]);
        }
        if ("embedding" in $$parsedSource) {
            $$parsedSource["embedding"] = $$createField1_0($$parsedSource["embedding"]);
        }
        return new AIProfilesDTO($$parsedSource as Partial<AIProfilesDTO>);
    }
}

export class ActivationResult {
    "status": ActivationStatus;
    "capability"?: CapabilityDTO | null;

    /** Creates a new ActivationResult instance. */
    constructor($$source: Partial<ActivationResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = ActivationStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ActivationResult {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capability" in $$parsedSource) {
            $$parsedSource["capability"] = $$createField1_0($$parsedSource["capability"]);
        }
        return new ActivationResult($$parsedSource as Partial<ActivationResult>);
    }
}

export enum ActivationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActivationActive = "active",
    ActivationCancelled = "cancelled",
};

export class CapabilityDTO {
    "sessionId": session$0.SessionID;
    "workspaceId": workspaceid$0.WorkspaceID;
    "generation": session$0.Generation;
    "display": DisplayDTO;

    /** Creates a new CapabilityDTO instance. */
    constructor($$source: Partial<CapabilityDTO> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("display" in $$source)) {
            this["display"] = (new DisplayDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapabilityDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CapabilityDTO {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("display" in $$parsedSource) {
            $$parsedSource["display"] = $$createField3_0($$parsedSource["display"]);
        }
        return new CapabilityDTO($$parsedSource as Partial<CapabilityDTO>);
    }
}

export class ChatCompletionDTO {
    "requestId": string;
    "conversationId": string;

    /** Creates a new ChatCompletionDTO instance. */
    constructor($$source: Partial<ChatCompletionDTO> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatCompletionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatCompletionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatCompletionDTO($$parsedSource as Partial<ChatCompletionDTO>);
    }
}

export class ChatHistoryOptionsDTO {
    "include": boolean;
    "persist": boolean;

    /** Creates a new ChatHistoryOptionsDTO instance. */
    constructor($$source: Partial<ChatHistoryOptionsDTO> = {}) {
        if (!("include" in $$source)) {
            this["include"] = false;
        }
        if (!("persist" in $$source)) {
            this["persist"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatHistoryOptionsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatHistoryOptionsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatHistoryOptionsDTO($$parsedSource as Partial<ChatHistoryOptionsDTO>);
    }
}

export class ChatRequestDTO {
    "session": SessionReferenceDTO;
    "requestId": string;
    "conversationId": string;
    "retryOfAttemptId"?: string;
    "question": string;
    "profiles": ProfileSelectionDTO;
    "history": ChatHistoryOptionsDTO;
    "selectedPath"?: string;
    "linkedPaths"?: string[];

    /** Creates a new ChatRequestDTO instance. */
    constructor($$source: Partial<ChatRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("question" in $$source)) {
            this["question"] = "";
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = (new ProfileSelectionDTO());
        }
        if (!("history" in $$source)) {
            this["history"] = (new ChatHistoryOptionsDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatRequestDTO {
        const $$createField0_0 = $$createType5;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType7;
        const $$createField8_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField5_0($$parsedSource["profiles"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField6_0($$parsedSource["history"]);
        }
        if ("linkedPaths" in $$parsedSource) {
            $$parsedSource["linkedPaths"] = $$createField8_0($$parsedSource["linkedPaths"]);
        }
        return new ChatRequestDTO($$parsedSource as Partial<ChatRequestDTO>);
    }
}

export class CitationNoteDTO {
    "path": string;
    "heading": string;
    "content": string;

    /** Creates a new CitationNoteDTO instance. */
    constructor($$source: Partial<CitationNoteDTO> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("heading" in $$source)) {
            this["heading"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CitationNoteDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CitationNoteDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CitationNoteDTO($$parsedSource as Partial<CitationNoteDTO>);
    }
}

export class CitationReadRequestDTO {
    "session": SessionReferenceDTO;
    "requestId": string;
    "citationId": string;

    /** Creates a new CitationReadRequestDTO instance. */
    constructor($$source: Partial<CitationReadRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("citationId" in $$source)) {
            this["citationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CitationReadRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CitationReadRequestDTO {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new CitationReadRequestDTO($$parsedSource as Partial<CitationReadRequestDTO>);
    }
}

export class ConfirmSessionCredentialRequestDTO {
    "nonce": string;
    "secret": string;

    /** Creates a new ConfirmSessionCredentialRequestDTO instance. */
    constructor($$source: Partial<ConfirmSessionCredentialRequestDTO> = {}) {
        if (!("nonce" in $$source)) {
            this["nonce"] = "";
        }
        if (!("secret" in $$source)) {
            this["secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfirmSessionCredentialRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfirmSessionCredentialRequestDTO {
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("secret" in $$parsedSource) {
            $$parsedSource["secret"] = $$createField1_0($$parsedSource["secret"]);
        }
        return new ConfirmSessionCredentialRequestDTO($$parsedSource as Partial<ConfirmSessionCredentialRequestDTO>);
    }
}

export class CredentialChallengeDTO {
    "nonce": string;
    "reason": string;
    "expiresAt": time$0.Time;

    /** Creates a new CredentialChallengeDTO instance. */
    constructor($$source: Partial<CredentialChallengeDTO> = {}) {
        if (!("nonce" in $$source)) {
            this["nonce"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialChallengeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialChallengeDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialChallengeDTO($$parsedSource as Partial<CredentialChallengeDTO>);
    }
}

export class CredentialDeleteResultDTO {
    "deleted": boolean;
    "status": string;

    /** Creates a new CredentialDeleteResultDTO instance. */
    constructor($$source: Partial<CredentialDeleteResultDTO> = {}) {
        if (!("deleted" in $$source)) {
            this["deleted"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialDeleteResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialDeleteResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialDeleteResultDTO($$parsedSource as Partial<CredentialDeleteResultDTO>);
    }
}

export class CredentialReferenceDTO {
    "credentialRef": string;

    /** Creates a new CredentialReferenceDTO instance. */
    constructor($$source: Partial<CredentialReferenceDTO> = {}) {
        if (!("credentialRef" in $$source)) {
            this["credentialRef"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialReferenceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialReferenceDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialReferenceDTO($$parsedSource as Partial<CredentialReferenceDTO>);
    }
}

export class CredentialSaveResultDTO {
    "disposition": string;
    "challenge"?: CredentialChallengeDTO | null;

    /** Creates a new CredentialSaveResultDTO instance. */
    constructor($$source: Partial<CredentialSaveResultDTO> = {}) {
        if (!("disposition" in $$source)) {
            this["disposition"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialSaveResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialSaveResultDTO {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("challenge" in $$parsedSource) {
            $$parsedSource["challenge"] = $$createField1_0($$parsedSource["challenge"]);
        }
        return new CredentialSaveResultDTO($$parsedSource as Partial<CredentialSaveResultDTO>);
    }
}

export class CredentialStatusDTO {
    "status": string;

    /** Creates a new CredentialStatusDTO instance. */
    constructor($$source: Partial<CredentialStatusDTO> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialStatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialStatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialStatusDTO($$parsedSource as Partial<CredentialStatusDTO>);
    }
}

export class DeleteAIProfileRequestDTO {
    "role": string;
    "id": string;

    /** Creates a new DeleteAIProfileRequestDTO instance. */
    constructor($$source: Partial<DeleteAIProfileRequestDTO> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteAIProfileRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteAIProfileRequestDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteAIProfileRequestDTO($$parsedSource as Partial<DeleteAIProfileRequestDTO>);
    }
}

export class DisplayDTO {
    "label": string;

    /** Creates a new DisplayDTO instance. */
    constructor($$source: Partial<DisplayDTO> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisplayDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DisplayDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisplayDTO($$parsedSource as Partial<DisplayDTO>);
    }
}

export class EmbeddingConsentRequestDTO {
    "session": SessionReferenceDTO;
    "embeddingProfileId": string;

    /** Creates a new EmbeddingConsentRequestDTO instance. */
    constructor($$source: Partial<EmbeddingConsentRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("embeddingProfileId" in $$source)) {
            this["embeddingProfileId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmbeddingConsentRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): EmbeddingConsentRequestDTO {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new EmbeddingConsentRequestDTO($$parsedSource as Partial<EmbeddingConsentRequestDTO>);
    }
}

export class EmbeddingConsentResultDTO {
    "profileId": string;
    "granted": boolean;
    "kind": string;
    "disclosureVersion": number;

    /** Creates a new EmbeddingConsentResultDTO instance. */
    constructor($$source: Partial<EmbeddingConsentResultDTO> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("granted" in $$source)) {
            this["granted"] = false;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("disclosureVersion" in $$source)) {
            this["disclosureVersion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmbeddingConsentResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): EmbeddingConsentResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmbeddingConsentResultDTO($$parsedSource as Partial<EmbeddingConsentResultDTO>);
    }
}

export class HistoryCitationDTO {
    "id": string;
    "label": string;

    /** Creates a new HistoryCitationDTO instance. */
    constructor($$source: Partial<HistoryCitationDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryCitationDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryCitationDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryCitationDTO($$parsedSource as Partial<HistoryCitationDTO>);
    }
}

export class HistoryConversationRequestDTO {
    "session": SessionReferenceDTO;
    "conversationId": string;

    /** Creates a new HistoryConversationRequestDTO instance. */
    constructor($$source: Partial<HistoryConversationRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryConversationRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryConversationRequestDTO {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new HistoryConversationRequestDTO($$parsedSource as Partial<HistoryConversationRequestDTO>);
    }
}

export class HistoryDeleteAllResultDTO {
    "deletedIds": string[];
    "durableDeletedIds": string[];
    "uncertainDeletedIds": string[];
    "remainingIds": string[];
    "durable": boolean;

    /** Creates a new HistoryDeleteAllResultDTO instance. */
    constructor($$source: Partial<HistoryDeleteAllResultDTO> = {}) {
        if (!("deletedIds" in $$source)) {
            this["deletedIds"] = [];
        }
        if (!("durableDeletedIds" in $$source)) {
            this["durableDeletedIds"] = [];
        }
        if (!("uncertainDeletedIds" in $$source)) {
            this["uncertainDeletedIds"] = [];
        }
        if (!("remainingIds" in $$source)) {
            this["remainingIds"] = [];
        }
        if (!("durable" in $$source)) {
            this["durable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryDeleteAllResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryDeleteAllResultDTO {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deletedIds" in $$parsedSource) {
            $$parsedSource["deletedIds"] = $$createField0_0($$parsedSource["deletedIds"]);
        }
        if ("durableDeletedIds" in $$parsedSource) {
            $$parsedSource["durableDeletedIds"] = $$createField1_0($$parsedSource["durableDeletedIds"]);
        }
        if ("uncertainDeletedIds" in $$parsedSource) {
            $$parsedSource["uncertainDeletedIds"] = $$createField2_0($$parsedSource["uncertainDeletedIds"]);
        }
        if ("remainingIds" in $$parsedSource) {
            $$parsedSource["remainingIds"] = $$createField3_0($$parsedSource["remainingIds"]);
        }
        return new HistoryDeleteAllResultDTO($$parsedSource as Partial<HistoryDeleteAllResultDTO>);
    }
}

export class HistoryDeleteResultDTO {
    "removed": boolean;
    "durable": boolean;

    /** Creates a new HistoryDeleteResultDTO instance. */
    constructor($$source: Partial<HistoryDeleteResultDTO> = {}) {
        if (!("removed" in $$source)) {
            this["removed"] = false;
        }
        if (!("durable" in $$source)) {
            this["durable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryDeleteResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryDeleteResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryDeleteResultDTO($$parsedSource as Partial<HistoryDeleteResultDTO>);
    }
}

export class HistoryListDTO {
    "conversations": HistoryMetadataDTO[];

    /** Creates a new HistoryListDTO instance. */
    constructor($$source: Partial<HistoryListDTO> = {}) {
        if (!("conversations" in $$source)) {
            this["conversations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryListDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryListDTO {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conversations" in $$parsedSource) {
            $$parsedSource["conversations"] = $$createField0_0($$parsedSource["conversations"]);
        }
        return new HistoryListDTO($$parsedSource as Partial<HistoryListDTO>);
    }
}

export class HistoryMetadataDTO {
    "conversationId": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "attempts": number;
    "latestStatus": string;

    /** Creates a new HistoryMetadataDTO instance. */
    constructor($$source: Partial<HistoryMetadataDTO> = {}) {
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("attempts" in $$source)) {
            this["attempts"] = 0;
        }
        if (!("latestStatus" in $$source)) {
            this["latestStatus"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryMetadataDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryMetadataDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryMetadataDTO($$parsedSource as Partial<HistoryMetadataDTO>);
    }
}

export class HistoryRecordDTO {
    "conversationId": string;
    "attemptId": string;
    "retryOfAttemptId"?: string;
    "createdAt": time$0.Time;
    "finishedAt": time$0.Time;
    "status": string;
    "userMessage"?: string;
    "assistantOutput"?: string;
    "citations"?: HistoryCitationDTO[];
    "errorCode"?: string;
    "usage": HistoryUsageDTO;

    /** Creates a new HistoryRecordDTO instance. */
    constructor($$source: Partial<HistoryRecordDTO> = {}) {
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("attemptId" in $$source)) {
            this["attemptId"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("usage" in $$source)) {
            this["usage"] = (new HistoryUsageDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryRecordDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryRecordDTO {
        const $$createField8_0 = $$createType14;
        const $$createField10_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("citations" in $$parsedSource) {
            $$parsedSource["citations"] = $$createField8_0($$parsedSource["citations"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField10_0($$parsedSource["usage"]);
        }
        return new HistoryRecordDTO($$parsedSource as Partial<HistoryRecordDTO>);
    }
}

export class HistoryRecordsDTO {
    "records": HistoryRecordDTO[];

    /** Creates a new HistoryRecordsDTO instance. */
    constructor($$source: Partial<HistoryRecordsDTO> = {}) {
        if (!("records" in $$source)) {
            this["records"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryRecordsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryRecordsDTO {
        const $$createField0_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField0_0($$parsedSource["records"]);
        }
        return new HistoryRecordsDTO($$parsedSource as Partial<HistoryRecordsDTO>);
    }
}

export class HistoryStatusDTO {
    "enabled": boolean;

    /** Creates a new HistoryStatusDTO instance. */
    constructor($$source: Partial<HistoryStatusDTO> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryStatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryStatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryStatusDTO($$parsedSource as Partial<HistoryStatusDTO>);
    }
}

export class HistoryUsageDTO {
    "inputTokens": number;
    "outputTokens": number;

    /** Creates a new HistoryUsageDTO instance. */
    constructor($$source: Partial<HistoryUsageDTO> = {}) {
        if (!("inputTokens" in $$source)) {
            this["inputTokens"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            this["outputTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryUsageDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryUsageDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryUsageDTO($$parsedSource as Partial<HistoryUsageDTO>);
    }
}

export class IndexCancelResultDTO {
    "cancelled": boolean;

    /** Creates a new IndexCancelResultDTO instance. */
    constructor($$source: Partial<IndexCancelResultDTO> = {}) {
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexCancelResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexCancelResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexCancelResultDTO($$parsedSource as Partial<IndexCancelResultDTO>);
    }
}

export class IndexRequestDTO {
    "session": SessionReferenceDTO;
    "embeddingProfileId": string;

    /** Creates a new IndexRequestDTO instance. */
    constructor($$source: Partial<IndexRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("embeddingProfileId" in $$source)) {
            this["embeddingProfileId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexRequestDTO {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new IndexRequestDTO($$parsedSource as Partial<IndexRequestDTO>);
    }
}

export class IndexStatusDTO {
    "state": string;
    "chunks": number;
    "vectors": number;
    "dimensions": number;

    /** Creates a new IndexStatusDTO instance. */
    constructor($$source: Partial<IndexStatusDTO> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("chunks" in $$source)) {
            this["chunks"] = 0;
        }
        if (!("vectors" in $$source)) {
            this["vectors"] = 0;
        }
        if (!("dimensions" in $$source)) {
            this["dimensions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexStatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexStatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexStatusDTO($$parsedSource as Partial<IndexStatusDTO>);
    }
}

export class ProfileDeleteResultDTO {
    "removed": boolean;
    "role": string;
    "id": string;

    /** Creates a new ProfileDeleteResultDTO instance. */
    constructor($$source: Partial<ProfileDeleteResultDTO> = {}) {
        if (!("removed" in $$source)) {
            this["removed"] = false;
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDeleteResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileDeleteResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileDeleteResultDTO($$parsedSource as Partial<ProfileDeleteResultDTO>);
    }
}

export class ProfileSelectionDTO {
    "chatProfileId": string;
    "embeddingProfileId"?: string;

    /** Creates a new ProfileSelectionDTO instance. */
    constructor($$source: Partial<ProfileSelectionDTO> = {}) {
        if (!("chatProfileId" in $$source)) {
            this["chatProfileId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSelectionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSelectionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSelectionDTO($$parsedSource as Partial<ProfileSelectionDTO>);
    }
}

export class SaveAIProfileRequestDTO {
    "id": string;
    "role": string;
    "kind": string;
    "label": string;
    "model": string;
    "baseUrl": string;
    "credentialRef"?: string;
    "timeoutMs": number;
    "maxInputChars": number;
    "maxHistoryChars": number;
    "maxEvidenceChars": number;
    "maxOutputTokens": number;
    "dimensions"?: number;

    /** Creates a new SaveAIProfileRequestDTO instance. */
    constructor($$source: Partial<SaveAIProfileRequestDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("timeoutMs" in $$source)) {
            this["timeoutMs"] = 0;
        }
        if (!("maxInputChars" in $$source)) {
            this["maxInputChars"] = 0;
        }
        if (!("maxHistoryChars" in $$source)) {
            this["maxHistoryChars"] = 0;
        }
        if (!("maxEvidenceChars" in $$source)) {
            this["maxEvidenceChars"] = 0;
        }
        if (!("maxOutputTokens" in $$source)) {
            this["maxOutputTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveAIProfileRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveAIProfileRequestDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveAIProfileRequestDTO($$parsedSource as Partial<SaveAIProfileRequestDTO>);
    }
}

export class SaveCredentialRequestDTO {
    "credentialRef": string;
    "secret": string;

    /** Creates a new SaveCredentialRequestDTO instance. */
    constructor($$source: Partial<SaveCredentialRequestDTO> = {}) {
        if (!("credentialRef" in $$source)) {
            this["credentialRef"] = "";
        }
        if (!("secret" in $$source)) {
            this["secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveCredentialRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveCredentialRequestDTO {
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("secret" in $$parsedSource) {
            $$parsedSource["secret"] = $$createField1_0($$parsedSource["secret"]);
        }
        return new SaveCredentialRequestDTO($$parsedSource as Partial<SaveCredentialRequestDTO>);
    }
}

export class SessionReferenceDTO {
    "sessionId": session$0.SessionID;
    "generation": session$0.Generation;

    /** Creates a new SessionReferenceDTO instance. */
    constructor($$source: Partial<SessionReferenceDTO> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionReferenceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionReferenceDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionReferenceDTO($$parsedSource as Partial<SessionReferenceDTO>);
    }
}

export class SetHistoryEnabledRequestDTO {
    "session": SessionReferenceDTO;
    "enabled": boolean;

    /** Creates a new SetHistoryEnabledRequestDTO instance. */
    constructor($$source: Partial<SetHistoryEnabledRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetHistoryEnabledRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SetHistoryEnabledRequestDTO {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new SetHistoryEnabledRequestDTO($$parsedSource as Partial<SetHistoryEnabledRequestDTO>);
    }
}

export class WorkspaceTreeDTO {
    "nodes": WorkspaceTreeNodeDTO[];
    "warnings": WorkspaceTreeWarningDTO[];
    "truncated": boolean;

    /** Creates a new WorkspaceTreeDTO instance. */
    constructor($$source: Partial<WorkspaceTreeDTO> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTreeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceTreeDTO {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField1_0($$parsedSource["warnings"]);
        }
        return new WorkspaceTreeDTO($$parsedSource as Partial<WorkspaceTreeDTO>);
    }
}

export class WorkspaceTreeNodeDTO {
    "id": string;
    "name": string;
    "path": string;
    "kind": string;
    "size"?: number;
    "children"?: WorkspaceTreeNodeDTO[];
    "truncated"?: boolean;

    /** Creates a new WorkspaceTreeNodeDTO instance. */
    constructor($$source: Partial<WorkspaceTreeNodeDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTreeNodeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceTreeNodeDTO {
        const $$createField5_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new WorkspaceTreeNodeDTO($$parsedSource as Partial<WorkspaceTreeNodeDTO>);
    }
}

export class WorkspaceTreeWarningDTO {
    "path": string;
    "code": string;

    /** Creates a new WorkspaceTreeWarningDTO instance. */
    constructor($$source: Partial<WorkspaceTreeWarningDTO> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTreeWarningDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceTreeWarningDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceTreeWarningDTO($$parsedSource as Partial<WorkspaceTreeWarningDTO>);
    }
}

// Private type creation functions
const $$createType0 = AIProfileDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = CapabilityDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = DisplayDTO.createFrom;
const $$createType5 = SessionReferenceDTO.createFrom;
const $$createType6 = ProfileSelectionDTO.createFrom;
const $$createType7 = ChatHistoryOptionsDTO.createFrom;
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = CredentialChallengeDTO.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = HistoryMetadataDTO.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = HistoryCitationDTO.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = HistoryUsageDTO.createFrom;
const $$createType16 = HistoryRecordDTO.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = WorkspaceTreeNodeDTO.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = WorkspaceTreeWarningDTO.createFrom;
const $$createType21 = $Create.Array($$createType20);
