// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "./history/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "./session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaceid$0 from "./workspaceid/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appstate$0 from "../appstate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class AIProfileDTO {
    "schemaVersion": number;
    "id": string;
    "role": string;
    "kind": string;
    "label": string;
    "model": string;
    "baseUrl": string;
    "credentialRef"?: string;
    "timeoutMs": number;
    "maxInputChars": number;
    "maxHistoryChars": number;
    "maxEvidenceChars": number;
    "maxOutputTokens": number;
    "dimensions"?: number;

    /** Creates a new AIProfileDTO instance. */
    constructor($$source: Partial<AIProfileDTO> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("timeoutMs" in $$source)) {
            this["timeoutMs"] = 0;
        }
        if (!("maxInputChars" in $$source)) {
            this["maxInputChars"] = 0;
        }
        if (!("maxHistoryChars" in $$source)) {
            this["maxHistoryChars"] = 0;
        }
        if (!("maxEvidenceChars" in $$source)) {
            this["maxEvidenceChars"] = 0;
        }
        if (!("maxOutputTokens" in $$source)) {
            this["maxOutputTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProfileDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProfileDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIProfileDTO($$parsedSource as Partial<AIProfileDTO>);
    }
}

export class AIProfilesDTO {
    "chat"?: AIProfileDTO | null;
    "embedding"?: AIProfileDTO | null;

    /** Creates a new AIProfilesDTO instance. */
    constructor($$source: Partial<AIProfilesDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProfilesDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProfilesDTO {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chat" in $$parsedSource) {
            $$parsedSource["chat"] = $$createField0_0($$parsedSource["chat"]);
        }
        if ("embedding" in $$parsedSource) {
            $$parsedSource["embedding"] = $$createField1_0($$parsedSource["embedding"]);
        }
        return new AIProfilesDTO($$parsedSource as Partial<AIProfilesDTO>);
    }
}

export class ArtifactLocatorV1DTO {
    "version": number;
    "kind": string;
    "relativePath": string;

    /** Creates a new ArtifactLocatorV1DTO instance. */
    constructor($$source: Partial<ArtifactLocatorV1DTO> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtifactLocatorV1DTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ArtifactLocatorV1DTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArtifactLocatorV1DTO($$parsedSource as Partial<ArtifactLocatorV1DTO>);
    }
}

export class CapabilityDTO {
    "sessionId": session$0.SessionID;
    "workspaceId": workspaceid$0.WorkspaceID;
    "generation": session$0.Generation;
    "display": DisplayDTO;
    "accessMode": session$0.AccessMode;

    /** Creates a new CapabilityDTO instance. */
    constructor($$source: Partial<CapabilityDTO> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("display" in $$source)) {
            this["display"] = (new DisplayDTO());
        }
        if (!("accessMode" in $$source)) {
            this["accessMode"] = session$0.AccessMode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapabilityDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CapabilityDTO {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("display" in $$parsedSource) {
            $$parsedSource["display"] = $$createField3_0($$parsedSource["display"]);
        }
        return new CapabilityDTO($$parsedSource as Partial<CapabilityDTO>);
    }
}

export class ChatCompletionDTO {
    "requestId": string;
    "conversationId": string;

    /** Creates a new ChatCompletionDTO instance. */
    constructor($$source: Partial<ChatCompletionDTO> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatCompletionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatCompletionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatCompletionDTO($$parsedSource as Partial<ChatCompletionDTO>);
    }
}

export class ChatHistoryOptionsDTO {
    "include": boolean;
    "persist": boolean;

    /** Creates a new ChatHistoryOptionsDTO instance. */
    constructor($$source: Partial<ChatHistoryOptionsDTO> = {}) {
        if (!("include" in $$source)) {
            this["include"] = false;
        }
        if (!("persist" in $$source)) {
            this["persist"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatHistoryOptionsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatHistoryOptionsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatHistoryOptionsDTO($$parsedSource as Partial<ChatHistoryOptionsDTO>);
    }
}

export class ChatRequestDTO {
    "session": SessionReferenceDTO;
    "requestId": string;
    "conversationId": string;
    "retryOfAttemptId"?: string;
    "question": string;
    "profiles": ProfileSelectionDTO;
    "history": ChatHistoryOptionsDTO;
    "selectedPath"?: string;
    "linkedPaths"?: string[];

    /** Creates a new ChatRequestDTO instance. */
    constructor($$source: Partial<ChatRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("question" in $$source)) {
            this["question"] = "";
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = (new ProfileSelectionDTO());
        }
        if (!("history" in $$source)) {
            this["history"] = (new ChatHistoryOptionsDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatRequestDTO {
        const $$createField0_0 = $$createType3;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField5_0($$parsedSource["profiles"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField6_0($$parsedSource["history"]);
        }
        if ("linkedPaths" in $$parsedSource) {
            $$parsedSource["linkedPaths"] = $$createField8_0($$parsedSource["linkedPaths"]);
        }
        return new ChatRequestDTO($$parsedSource as Partial<ChatRequestDTO>);
    }
}

export class CitationNoteDTO {
    "path": string;
    "heading": string;
    "content": string;

    /** Creates a new CitationNoteDTO instance. */
    constructor($$source: Partial<CitationNoteDTO> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("heading" in $$source)) {
            this["heading"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CitationNoteDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CitationNoteDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CitationNoteDTO($$parsedSource as Partial<CitationNoteDTO>);
    }
}

export class CitationReadRequestDTO {
    "session": SessionReferenceDTO;
    "requestId": string;
    "citationId": string;

    /** Creates a new CitationReadRequestDTO instance. */
    constructor($$source: Partial<CitationReadRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("citationId" in $$source)) {
            this["citationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CitationReadRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CitationReadRequestDTO {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new CitationReadRequestDTO($$parsedSource as Partial<CitationReadRequestDTO>);
    }
}

export class ConfirmSessionCredentialRequestDTO {
    "nonce": string;
    "secret": string;

    /** Creates a new ConfirmSessionCredentialRequestDTO instance. */
    constructor($$source: Partial<ConfirmSessionCredentialRequestDTO> = {}) {
        if (!("nonce" in $$source)) {
            this["nonce"] = "";
        }
        if (!("secret" in $$source)) {
            this["secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfirmSessionCredentialRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfirmSessionCredentialRequestDTO {
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("secret" in $$parsedSource) {
            $$parsedSource["secret"] = $$createField1_0($$parsedSource["secret"]);
        }
        return new ConfirmSessionCredentialRequestDTO($$parsedSource as Partial<ConfirmSessionCredentialRequestDTO>);
    }
}

export enum ContinuityStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContinuityLoaded = "loaded",
    ContinuityEmpty = "empty",
    ContinuityUnavailable = "unavailable",
};

export class CredentialChallengeDTO {
    "nonce": string;
    "reason": string;
    "expiresAt": time$0.Time;

    /** Creates a new CredentialChallengeDTO instance. */
    constructor($$source: Partial<CredentialChallengeDTO> = {}) {
        if (!("nonce" in $$source)) {
            this["nonce"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialChallengeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialChallengeDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialChallengeDTO($$parsedSource as Partial<CredentialChallengeDTO>);
    }
}

export class CredentialDeleteResultDTO {
    "deleted": boolean;
    "status": string;

    /** Creates a new CredentialDeleteResultDTO instance. */
    constructor($$source: Partial<CredentialDeleteResultDTO> = {}) {
        if (!("deleted" in $$source)) {
            this["deleted"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialDeleteResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialDeleteResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialDeleteResultDTO($$parsedSource as Partial<CredentialDeleteResultDTO>);
    }
}

export class CredentialReferenceDTO {
    "credentialRef": string;

    /** Creates a new CredentialReferenceDTO instance. */
    constructor($$source: Partial<CredentialReferenceDTO> = {}) {
        if (!("credentialRef" in $$source)) {
            this["credentialRef"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialReferenceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialReferenceDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialReferenceDTO($$parsedSource as Partial<CredentialReferenceDTO>);
    }
}

export class CredentialSaveResultDTO {
    "disposition": string;
    "challenge"?: CredentialChallengeDTO | null;

    /** Creates a new CredentialSaveResultDTO instance. */
    constructor($$source: Partial<CredentialSaveResultDTO> = {}) {
        if (!("disposition" in $$source)) {
            this["disposition"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialSaveResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialSaveResultDTO {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("challenge" in $$parsedSource) {
            $$parsedSource["challenge"] = $$createField1_0($$parsedSource["challenge"]);
        }
        return new CredentialSaveResultDTO($$parsedSource as Partial<CredentialSaveResultDTO>);
    }
}

export class CredentialStatusDTO {
    "status": string;

    /** Creates a new CredentialStatusDTO instance. */
    constructor($$source: Partial<CredentialStatusDTO> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialStatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialStatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialStatusDTO($$parsedSource as Partial<CredentialStatusDTO>);
    }
}

export class DeleteAIProfileRequestDTO {
    "role": string;
    "id": string;

    /** Creates a new DeleteAIProfileRequestDTO instance. */
    constructor($$source: Partial<DeleteAIProfileRequestDTO> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteAIProfileRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteAIProfileRequestDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteAIProfileRequestDTO($$parsedSource as Partial<DeleteAIProfileRequestDTO>);
    }
}

export class DisplayDTO {
    "label": string;

    /** Creates a new DisplayDTO instance. */
    constructor($$source: Partial<DisplayDTO> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisplayDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DisplayDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisplayDTO($$parsedSource as Partial<DisplayDTO>);
    }
}

export class EmbeddingConsentRequestDTO {
    "session": SessionReferenceDTO;
    "embeddingProfileId": string;

    /** Creates a new EmbeddingConsentRequestDTO instance. */
    constructor($$source: Partial<EmbeddingConsentRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("embeddingProfileId" in $$source)) {
            this["embeddingProfileId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmbeddingConsentRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): EmbeddingConsentRequestDTO {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new EmbeddingConsentRequestDTO($$parsedSource as Partial<EmbeddingConsentRequestDTO>);
    }
}

export class EmbeddingConsentResultDTO {
    "profileId": string;
    "granted": boolean;
    "kind": string;
    "disclosureVersion": number;

    /** Creates a new EmbeddingConsentResultDTO instance. */
    constructor($$source: Partial<EmbeddingConsentResultDTO> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("granted" in $$source)) {
            this["granted"] = false;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("disclosureVersion" in $$source)) {
            this["disclosureVersion"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmbeddingConsentResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): EmbeddingConsentResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmbeddingConsentResultDTO($$parsedSource as Partial<EmbeddingConsentResultDTO>);
    }
}

export class FindRecentLibraryRequestDTO {
    "workspaceId": workspaceid$0.WorkspaceID;

    /** Creates a new FindRecentLibraryRequestDTO instance. */
    constructor($$source: Partial<FindRecentLibraryRequestDTO> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FindRecentLibraryRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): FindRecentLibraryRequestDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FindRecentLibraryRequestDTO($$parsedSource as Partial<FindRecentLibraryRequestDTO>);
    }
}

export class HistoryCitationDTO {
    "id": string;
    "label": string;

    /** Creates a new HistoryCitationDTO instance. */
    constructor($$source: Partial<HistoryCitationDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryCitationDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryCitationDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryCitationDTO($$parsedSource as Partial<HistoryCitationDTO>);
    }
}

export class HistoryConversationRequestDTO {
    "session": SessionReferenceDTO;
    "conversationId": string;

    /** Creates a new HistoryConversationRequestDTO instance. */
    constructor($$source: Partial<HistoryConversationRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryConversationRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryConversationRequestDTO {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new HistoryConversationRequestDTO($$parsedSource as Partial<HistoryConversationRequestDTO>);
    }
}

export class HistoryDeleteAllResultDTO {
    "deletedIds": string[];
    "durableDeletedIds": string[];
    "uncertainDeletedIds": string[];
    "remainingIds": string[];
    "durable": boolean;

    /** Creates a new HistoryDeleteAllResultDTO instance. */
    constructor($$source: Partial<HistoryDeleteAllResultDTO> = {}) {
        if (!("deletedIds" in $$source)) {
            this["deletedIds"] = [];
        }
        if (!("durableDeletedIds" in $$source)) {
            this["durableDeletedIds"] = [];
        }
        if (!("uncertainDeletedIds" in $$source)) {
            this["uncertainDeletedIds"] = [];
        }
        if (!("remainingIds" in $$source)) {
            this["remainingIds"] = [];
        }
        if (!("durable" in $$source)) {
            this["durable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryDeleteAllResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryDeleteAllResultDTO {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deletedIds" in $$parsedSource) {
            $$parsedSource["deletedIds"] = $$createField0_0($$parsedSource["deletedIds"]);
        }
        if ("durableDeletedIds" in $$parsedSource) {
            $$parsedSource["durableDeletedIds"] = $$createField1_0($$parsedSource["durableDeletedIds"]);
        }
        if ("uncertainDeletedIds" in $$parsedSource) {
            $$parsedSource["uncertainDeletedIds"] = $$createField2_0($$parsedSource["uncertainDeletedIds"]);
        }
        if ("remainingIds" in $$parsedSource) {
            $$parsedSource["remainingIds"] = $$createField3_0($$parsedSource["remainingIds"]);
        }
        return new HistoryDeleteAllResultDTO($$parsedSource as Partial<HistoryDeleteAllResultDTO>);
    }
}

export class HistoryDeleteResultDTO {
    "removed": boolean;
    "durable": boolean;

    /** Creates a new HistoryDeleteResultDTO instance. */
    constructor($$source: Partial<HistoryDeleteResultDTO> = {}) {
        if (!("removed" in $$source)) {
            this["removed"] = false;
        }
        if (!("durable" in $$source)) {
            this["durable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryDeleteResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryDeleteResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryDeleteResultDTO($$parsedSource as Partial<HistoryDeleteResultDTO>);
    }
}

export class HistoryListDTO {
    "conversations": HistoryMetadataDTO[];

    /** Creates a new HistoryListDTO instance. */
    constructor($$source: Partial<HistoryListDTO> = {}) {
        if (!("conversations" in $$source)) {
            this["conversations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryListDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryListDTO {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conversations" in $$parsedSource) {
            $$parsedSource["conversations"] = $$createField0_0($$parsedSource["conversations"]);
        }
        return new HistoryListDTO($$parsedSource as Partial<HistoryListDTO>);
    }
}

export class HistoryMetadataDTO {
    "conversationId": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "attempts": number;
    "latestStatus": string;

    /** Creates a new HistoryMetadataDTO instance. */
    constructor($$source: Partial<HistoryMetadataDTO> = {}) {
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("attempts" in $$source)) {
            this["attempts"] = 0;
        }
        if (!("latestStatus" in $$source)) {
            this["latestStatus"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryMetadataDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryMetadataDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryMetadataDTO($$parsedSource as Partial<HistoryMetadataDTO>);
    }
}

export class HistoryRecordDTO {
    "conversationId": string;
    "attemptId": string;
    "retryOfAttemptId"?: string;
    "createdAt": time$0.Time;
    "finishedAt": time$0.Time;
    "status": string;
    "userMessage"?: string;
    "assistantOutput"?: string;
    "citations"?: HistoryCitationDTO[];
    "errorCode"?: string;
    "usage": HistoryUsageDTO;

    /** Creates a new HistoryRecordDTO instance. */
    constructor($$source: Partial<HistoryRecordDTO> = {}) {
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("attemptId" in $$source)) {
            this["attemptId"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("usage" in $$source)) {
            this["usage"] = (new HistoryUsageDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryRecordDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryRecordDTO {
        const $$createField8_0 = $$createType12;
        const $$createField10_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("citations" in $$parsedSource) {
            $$parsedSource["citations"] = $$createField8_0($$parsedSource["citations"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField10_0($$parsedSource["usage"]);
        }
        return new HistoryRecordDTO($$parsedSource as Partial<HistoryRecordDTO>);
    }
}

export class HistoryRecordsDTO {
    "records": HistoryRecordDTO[];

    /** Creates a new HistoryRecordsDTO instance. */
    constructor($$source: Partial<HistoryRecordsDTO> = {}) {
        if (!("records" in $$source)) {
            this["records"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryRecordsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryRecordsDTO {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField0_0($$parsedSource["records"]);
        }
        return new HistoryRecordsDTO($$parsedSource as Partial<HistoryRecordsDTO>);
    }
}

export class HistoryStatusDTO {
    "enabled": boolean;

    /** Creates a new HistoryStatusDTO instance. */
    constructor($$source: Partial<HistoryStatusDTO> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryStatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryStatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryStatusDTO($$parsedSource as Partial<HistoryStatusDTO>);
    }
}

export class HistoryUsageDTO {
    "inputTokens": number;
    "outputTokens": number;

    /** Creates a new HistoryUsageDTO instance. */
    constructor($$source: Partial<HistoryUsageDTO> = {}) {
        if (!("inputTokens" in $$source)) {
            this["inputTokens"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            this["outputTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryUsageDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryUsageDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryUsageDTO($$parsedSource as Partial<HistoryUsageDTO>);
    }
}

export class IndexCancelResultDTO {
    "cancelled": boolean;

    /** Creates a new IndexCancelResultDTO instance. */
    constructor($$source: Partial<IndexCancelResultDTO> = {}) {
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexCancelResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexCancelResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexCancelResultDTO($$parsedSource as Partial<IndexCancelResultDTO>);
    }
}

export class IndexRequestDTO {
    "session": SessionReferenceDTO;
    "embeddingProfileId": string;

    /** Creates a new IndexRequestDTO instance. */
    constructor($$source: Partial<IndexRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("embeddingProfileId" in $$source)) {
            this["embeddingProfileId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexRequestDTO {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new IndexRequestDTO($$parsedSource as Partial<IndexRequestDTO>);
    }
}

export class IndexStatusDTO {
    "state": string;
    "chunks": number;
    "vectors": number;
    "dimensions": number;

    /** Creates a new IndexStatusDTO instance. */
    constructor($$source: Partial<IndexStatusDTO> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("chunks" in $$source)) {
            this["chunks"] = 0;
        }
        if (!("vectors" in $$source)) {
            this["vectors"] = 0;
        }
        if (!("dimensions" in $$source)) {
            this["dimensions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexStatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexStatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexStatusDTO($$parsedSource as Partial<IndexStatusDTO>);
    }
}

export class LatestHistoryDTO {
    "status": history$0.LatestStatus;
    "conversationId"?: string;
    "records"?: HistoryRecordDTO[];

    /** Creates a new LatestHistoryDTO instance. */
    constructor($$source: Partial<LatestHistoryDTO> = {}) {
        if (!("status" in $$source)) {
            this["status"] = history$0.LatestStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatestHistoryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LatestHistoryDTO {
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField2_0($$parsedSource["records"]);
        }
        return new LatestHistoryDTO($$parsedSource as Partial<LatestHistoryDTO>);
    }
}

export enum LibraryOperationKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LibraryOperationCreate = "create",
    LibraryOperationOpen = "open",
    LibraryOperationRecovery = "recovery",
};

export class LocationCapabilityDTO {
    "status": LocationStatus;
    "token"?: string;

    /** Creates a new LocationCapabilityDTO instance. */
    constructor($$source: Partial<LocationCapabilityDTO> = {}) {
        if (!("status" in $$source)) {
            this["status"] = LocationStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocationCapabilityDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocationCapabilityDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocationCapabilityDTO($$parsedSource as Partial<LocationCapabilityDTO>);
    }
}

export enum LocationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LocationApproved = "approved",
    LocationCancelled = "cancelled",
};

export class NoteContentDTO {
    "artifact": ArtifactLocatorV1DTO;
    "content": string;

    /** Creates a new NoteContentDTO instance. */
    constructor($$source: Partial<NoteContentDTO> = {}) {
        if (!("artifact" in $$source)) {
            this["artifact"] = (new ArtifactLocatorV1DTO());
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteContentDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): NoteContentDTO {
        const $$createField0_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artifact" in $$parsedSource) {
            $$parsedSource["artifact"] = $$createField0_0($$parsedSource["artifact"]);
        }
        return new NoteContentDTO($$parsedSource as Partial<NoteContentDTO>);
    }
}

export class PendingLibraryOperationDTO {
    "available": boolean;
    "recoveryId"?: string;
    "name"?: string;
    "phase"?: PendingLibraryPhase;

    /** Creates a new PendingLibraryOperationDTO instance. */
    constructor($$source: Partial<PendingLibraryOperationDTO> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingLibraryOperationDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PendingLibraryOperationDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PendingLibraryOperationDTO($$parsedSource as Partial<PendingLibraryOperationDTO>);
    }
}

export enum PendingLibraryPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PendingLibraryApproved = "approved",
    PendingLibraryMutating = "mutating",
    PendingLibraryCommitted = "committed",
};

export class PendingLibraryRemovalDTO {
    "removed": boolean;

    /** Creates a new PendingLibraryRemovalDTO instance. */
    constructor($$source: Partial<PendingLibraryRemovalDTO> = {}) {
        if (!("removed" in $$source)) {
            this["removed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingLibraryRemovalDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PendingLibraryRemovalDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PendingLibraryRemovalDTO($$parsedSource as Partial<PendingLibraryRemovalDTO>);
    }
}

export enum PreparationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PreparationReady = "ready",
    PreparationCancelled = "cancelled",
};

export class PreparedContinuityDTO {
    "prepared": PreparedLibraryDTO;
    "focus": WorkspaceFocus;
    "artifactStatus": ContinuityStatus;
    "artifact"?: NoteContentDTO | null;
    "historyStatus": history$0.LatestStatus;
    "conversationId"?: string;

    /** Creates a new PreparedContinuityDTO instance. */
    constructor($$source: Partial<PreparedContinuityDTO> = {}) {
        if (!("prepared" in $$source)) {
            this["prepared"] = (new PreparedLibraryDTO());
        }
        if (!("focus" in $$source)) {
            this["focus"] = WorkspaceFocus.$zero;
        }
        if (!("artifactStatus" in $$source)) {
            this["artifactStatus"] = ContinuityStatus.$zero;
        }
        if (!("historyStatus" in $$source)) {
            this["historyStatus"] = history$0.LatestStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreparedContinuityDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PreparedContinuityDTO {
        const $$createField0_0 = $$createType17;
        const $$createField3_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prepared" in $$parsedSource) {
            $$parsedSource["prepared"] = $$createField0_0($$parsedSource["prepared"]);
        }
        if ("artifact" in $$parsedSource) {
            $$parsedSource["artifact"] = $$createField3_0($$parsedSource["artifact"]);
        }
        return new PreparedContinuityDTO($$parsedSource as Partial<PreparedContinuityDTO>);
    }
}

export class PreparedLibraryAbortDTO {
    "cancelled": boolean;

    /** Creates a new PreparedLibraryAbortDTO instance. */
    constructor($$source: Partial<PreparedLibraryAbortDTO> = {}) {
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreparedLibraryAbortDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PreparedLibraryAbortDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreparedLibraryAbortDTO($$parsedSource as Partial<PreparedLibraryAbortDTO>);
    }
}

export class PreparedLibraryDTO {
    "status": PreparationStatus;
    "preparationToken"?: string;
    "kind"?: LibraryOperationKind;
    "snapshot": WorkspaceSnapshotDTO;

    /** Creates a new PreparedLibraryDTO instance. */
    constructor($$source: Partial<PreparedLibraryDTO> = {}) {
        if (!("status" in $$source)) {
            this["status"] = PreparationStatus.$zero;
        }
        if (!("snapshot" in $$source)) {
            this["snapshot"] = (new WorkspaceSnapshotDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreparedLibraryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PreparedLibraryDTO {
        const $$createField3_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField3_0($$parsedSource["snapshot"]);
        }
        return new PreparedLibraryDTO($$parsedSource as Partial<PreparedLibraryDTO>);
    }
}

export class ProfileDeleteResultDTO {
    "removed": boolean;
    "role": string;
    "id": string;

    /** Creates a new ProfileDeleteResultDTO instance. */
    constructor($$source: Partial<ProfileDeleteResultDTO> = {}) {
        if (!("removed" in $$source)) {
            this["removed"] = false;
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDeleteResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileDeleteResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileDeleteResultDTO($$parsedSource as Partial<ProfileDeleteResultDTO>);
    }
}

export class ProfileSelectionDTO {
    "chatProfileId": string;
    "embeddingProfileId"?: string;

    /** Creates a new ProfileSelectionDTO instance. */
    constructor($$source: Partial<ProfileSelectionDTO> = {}) {
        if (!("chatProfileId" in $$source)) {
            this["chatProfileId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSelectionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSelectionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSelectionDTO($$parsedSource as Partial<ProfileSelectionDTO>);
    }
}

export class ReadyCommitDTO {
    "status": ReadyCommitStatus;
    "capability"?: CapabilityDTO | null;
    "snapshot"?: WorkspaceSnapshotDTO | null;
    "pending"?: PendingLibraryOperationDTO | null;
    "recoveryRetained"?: boolean;
    "continuityWarning"?: boolean;

    /** Creates a new ReadyCommitDTO instance. */
    constructor($$source: Partial<ReadyCommitDTO> = {}) {
        if (!("status" in $$source)) {
            this["status"] = ReadyCommitStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadyCommitDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadyCommitDTO {
        const $$createField1_0 = $$createType22;
        const $$createField2_0 = $$createType23;
        const $$createField3_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capability" in $$parsedSource) {
            $$parsedSource["capability"] = $$createField1_0($$parsedSource["capability"]);
        }
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField2_0($$parsedSource["snapshot"]);
        }
        if ("pending" in $$parsedSource) {
            $$parsedSource["pending"] = $$createField3_0($$parsedSource["pending"]);
        }
        return new ReadyCommitDTO($$parsedSource as Partial<ReadyCommitDTO>);
    }
}

export enum ReadyCommitStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CommitCancelledBeforeCommit = "cancelled_before_commit",
    CommitCreatedAndActive = "created_and_active",
    CommitCreatedNotActive = "created_not_active",
    CommitOpenedAndActive = "opened_and_active",
};

export class RecentLibrariesDTO {
    "libraries": RecentLibraryDTO[];

    /** Creates a new RecentLibrariesDTO instance. */
    constructor($$source: Partial<RecentLibrariesDTO> = {}) {
        if (!("libraries" in $$source)) {
            this["libraries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentLibrariesDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentLibrariesDTO {
        const $$createField0_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("libraries" in $$parsedSource) {
            $$parsedSource["libraries"] = $$createField0_0($$parsedSource["libraries"]);
        }
        return new RecentLibrariesDTO($$parsedSource as Partial<RecentLibrariesDTO>);
    }
}

export class RecentLibraryDTO {
    "workspaceId": workspaceid$0.WorkspaceID;
    "label": string;
    "activatedAt": time$0.Time;
    "status": RecentLibraryStatus;
    "focus"?: WorkspaceFocus;

    /** Creates a new RecentLibraryDTO instance. */
    constructor($$source: Partial<RecentLibraryDTO> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("activatedAt" in $$source)) {
            this["activatedAt"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = RecentLibraryStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentLibraryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentLibraryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentLibraryDTO($$parsedSource as Partial<RecentLibraryDTO>);
    }
}

export class RecentLibraryRequestDTO {
    "workspaceId": workspaceid$0.WorkspaceID;

    /** Creates a new RecentLibraryRequestDTO instance. */
    constructor($$source: Partial<RecentLibraryRequestDTO> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentLibraryRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentLibraryRequestDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentLibraryRequestDTO($$parsedSource as Partial<RecentLibraryRequestDTO>);
    }
}

export enum RecentLibraryStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RecentLibraryAvailable = "available",
    RecentLibraryUnavailable = "unavailable",
};

export class RemoveRecentLibraryResultDTO {
    "removed": boolean;

    /** Creates a new RemoveRecentLibraryResultDTO instance. */
    constructor($$source: Partial<RemoveRecentLibraryResultDTO> = {}) {
        if (!("removed" in $$source)) {
            this["removed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoveRecentLibraryResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoveRecentLibraryResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoveRecentLibraryResultDTO($$parsedSource as Partial<RemoveRecentLibraryResultDTO>);
    }
}

export enum ResetConfirmationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ResetConfirmationReady = "ready",
    ResetConfirmationCancelled = "cancelled",
};

export class ResetRecentViewStateConfirmationDTO {
    "status": ResetConfirmationStatus;
    "token"?: string;

    /** Creates a new ResetRecentViewStateConfirmationDTO instance. */
    constructor($$source: Partial<ResetRecentViewStateConfirmationDTO> = {}) {
        if (!("status" in $$source)) {
            this["status"] = ResetConfirmationStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetRecentViewStateConfirmationDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetRecentViewStateConfirmationDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetRecentViewStateConfirmationDTO($$parsedSource as Partial<ResetRecentViewStateConfirmationDTO>);
    }
}

export class ResetRecentViewStateResultDTO {
    "status": appstate$0.ResetOutcome;

    /** Creates a new ResetRecentViewStateResultDTO instance. */
    constructor($$source: Partial<ResetRecentViewStateResultDTO> = {}) {
        if (!("status" in $$source)) {
            this["status"] = appstate$0.ResetOutcome.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetRecentViewStateResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetRecentViewStateResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetRecentViewStateResultDTO($$parsedSource as Partial<ResetRecentViewStateResultDTO>);
    }
}

export class RestoreRecentLibraryRequestDTO {
    "workspaceId": workspaceid$0.WorkspaceID;

    /** Creates a new RestoreRecentLibraryRequestDTO instance. */
    constructor($$source: Partial<RestoreRecentLibraryRequestDTO> = {}) {
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreRecentLibraryRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RestoreRecentLibraryRequestDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RestoreRecentLibraryRequestDTO($$parsedSource as Partial<RestoreRecentLibraryRequestDTO>);
    }
}

export class SaveAIProfileRequestDTO {
    "id": string;
    "role": string;
    "kind": string;
    "label": string;
    "model": string;
    "baseUrl": string;
    "credentialRef"?: string;
    "timeoutMs": number;
    "maxInputChars": number;
    "maxHistoryChars": number;
    "maxEvidenceChars": number;
    "maxOutputTokens": number;
    "dimensions"?: number;

    /** Creates a new SaveAIProfileRequestDTO instance. */
    constructor($$source: Partial<SaveAIProfileRequestDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("timeoutMs" in $$source)) {
            this["timeoutMs"] = 0;
        }
        if (!("maxInputChars" in $$source)) {
            this["maxInputChars"] = 0;
        }
        if (!("maxHistoryChars" in $$source)) {
            this["maxHistoryChars"] = 0;
        }
        if (!("maxEvidenceChars" in $$source)) {
            this["maxEvidenceChars"] = 0;
        }
        if (!("maxOutputTokens" in $$source)) {
            this["maxOutputTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveAIProfileRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveAIProfileRequestDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveAIProfileRequestDTO($$parsedSource as Partial<SaveAIProfileRequestDTO>);
    }
}

export class SaveCredentialRequestDTO {
    "credentialRef": string;
    "secret": string;

    /** Creates a new SaveCredentialRequestDTO instance. */
    constructor($$source: Partial<SaveCredentialRequestDTO> = {}) {
        if (!("credentialRef" in $$source)) {
            this["credentialRef"] = "";
        }
        if (!("secret" in $$source)) {
            this["secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveCredentialRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveCredentialRequestDTO {
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("secret" in $$parsedSource) {
            $$parsedSource["secret"] = $$createField1_0($$parsedSource["secret"]);
        }
        return new SaveCredentialRequestDTO($$parsedSource as Partial<SaveCredentialRequestDTO>);
    }
}

export class SaveWorkspaceViewRequestDTO {
    "session": SessionReferenceDTO;
    "focus": WorkspaceFocus;
    "artifact"?: ArtifactLocatorV1DTO | null;

    /** Creates a new SaveWorkspaceViewRequestDTO instance. */
    constructor($$source: Partial<SaveWorkspaceViewRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("focus" in $$source)) {
            this["focus"] = WorkspaceFocus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveWorkspaceViewRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveWorkspaceViewRequestDTO {
        const $$createField0_0 = $$createType3;
        const $$createField2_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("artifact" in $$parsedSource) {
            $$parsedSource["artifact"] = $$createField2_0($$parsedSource["artifact"]);
        }
        return new SaveWorkspaceViewRequestDTO($$parsedSource as Partial<SaveWorkspaceViewRequestDTO>);
    }
}

export class SessionReferenceDTO {
    "sessionId": session$0.SessionID;
    "generation": session$0.Generation;

    /** Creates a new SessionReferenceDTO instance. */
    constructor($$source: Partial<SessionReferenceDTO> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionReferenceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionReferenceDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionReferenceDTO($$parsedSource as Partial<SessionReferenceDTO>);
    }
}

export class SetHistoryEnabledRequestDTO {
    "session": SessionReferenceDTO;
    "enabled": boolean;

    /** Creates a new SetHistoryEnabledRequestDTO instance. */
    constructor($$source: Partial<SetHistoryEnabledRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetHistoryEnabledRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SetHistoryEnabledRequestDTO {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new SetHistoryEnabledRequestDTO($$parsedSource as Partial<SetHistoryEnabledRequestDTO>);
    }
}

export enum WorkspaceFocus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WorkspaceFocusChat = "chat",
    WorkspaceFocusNote = "note",
    WorkspaceFocusGraph = "graph",
};

export class WorkspaceGraphDTO {
    "nodes": WorkspaceGraphNodeDTO[];
    "edges": WorkspaceGraphEdgeDTO[];

    /** Creates a new WorkspaceGraphDTO instance. */
    constructor($$source: Partial<WorkspaceGraphDTO> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceGraphDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceGraphDTO {
        const $$createField0_0 = $$createType30;
        const $$createField1_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new WorkspaceGraphDTO($$parsedSource as Partial<WorkspaceGraphDTO>);
    }
}

export class WorkspaceGraphEdgeDTO {
    "from": string;
    "type": string;
    "to": string;

    /** Creates a new WorkspaceGraphEdgeDTO instance. */
    constructor($$source: Partial<WorkspaceGraphEdgeDTO> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceGraphEdgeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceGraphEdgeDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceGraphEdgeDTO($$parsedSource as Partial<WorkspaceGraphEdgeDTO>);
    }
}

export class WorkspaceGraphNodeDTO {
    "id": string;
    "title": string;
    "type": string;
    "path": string;
    "preview"?: string;

    /** Creates a new WorkspaceGraphNodeDTO instance. */
    constructor($$source: Partial<WorkspaceGraphNodeDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceGraphNodeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceGraphNodeDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceGraphNodeDTO($$parsedSource as Partial<WorkspaceGraphNodeDTO>);
    }
}

export class WorkspaceNoteRequestDTO {
    "session": SessionReferenceDTO;
    "artifact": ArtifactLocatorV1DTO;

    /** Creates a new WorkspaceNoteRequestDTO instance. */
    constructor($$source: Partial<WorkspaceNoteRequestDTO> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionReferenceDTO());
        }
        if (!("artifact" in $$source)) {
            this["artifact"] = (new ArtifactLocatorV1DTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceNoteRequestDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceNoteRequestDTO {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("artifact" in $$parsedSource) {
            $$parsedSource["artifact"] = $$createField1_0($$parsedSource["artifact"]);
        }
        return new WorkspaceNoteRequestDTO($$parsedSource as Partial<WorkspaceNoteRequestDTO>);
    }
}

export class WorkspaceSnapshotDTO {
    "display": DisplayDTO;
    "summary": WorkspaceSummaryDTO;
    "graph": WorkspaceGraphDTO;
    "tree": WorkspaceTreeDTO;
    "accessMode": session$0.AccessMode;
    "noteAvailable": boolean;
    "warnings": WorkspaceWarningDTO[];

    /** Creates a new WorkspaceSnapshotDTO instance. */
    constructor($$source: Partial<WorkspaceSnapshotDTO> = {}) {
        if (!("display" in $$source)) {
            this["display"] = (new DisplayDTO());
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new WorkspaceSummaryDTO());
        }
        if (!("graph" in $$source)) {
            this["graph"] = (new WorkspaceGraphDTO());
        }
        if (!("tree" in $$source)) {
            this["tree"] = (new WorkspaceTreeDTO());
        }
        if (!("accessMode" in $$source)) {
            this["accessMode"] = session$0.AccessMode.$zero;
        }
        if (!("noteAvailable" in $$source)) {
            this["noteAvailable"] = false;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceSnapshotDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceSnapshotDTO {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType33;
        const $$createField2_0 = $$createType34;
        const $$createField3_0 = $$createType35;
        const $$createField6_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("display" in $$parsedSource) {
            $$parsedSource["display"] = $$createField0_0($$parsedSource["display"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField1_0($$parsedSource["summary"]);
        }
        if ("graph" in $$parsedSource) {
            $$parsedSource["graph"] = $$createField2_0($$parsedSource["graph"]);
        }
        if ("tree" in $$parsedSource) {
            $$parsedSource["tree"] = $$createField3_0($$parsedSource["tree"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField6_0($$parsedSource["warnings"]);
        }
        return new WorkspaceSnapshotDTO($$parsedSource as Partial<WorkspaceSnapshotDTO>);
    }
}

export class WorkspaceSummaryDTO {
    "notes": number;
    "sources": number;
    "relationships": number;

    /** Creates a new WorkspaceSummaryDTO instance. */
    constructor($$source: Partial<WorkspaceSummaryDTO> = {}) {
        if (!("notes" in $$source)) {
            this["notes"] = 0;
        }
        if (!("sources" in $$source)) {
            this["sources"] = 0;
        }
        if (!("relationships" in $$source)) {
            this["relationships"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceSummaryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceSummaryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceSummaryDTO($$parsedSource as Partial<WorkspaceSummaryDTO>);
    }
}

export class WorkspaceTreeDTO {
    "nodes": WorkspaceTreeNodeDTO[];
    "warnings": WorkspaceTreeWarningDTO[];
    "truncated": boolean;

    /** Creates a new WorkspaceTreeDTO instance. */
    constructor($$source: Partial<WorkspaceTreeDTO> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTreeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceTreeDTO {
        const $$createField0_0 = $$createType39;
        const $$createField1_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField1_0($$parsedSource["warnings"]);
        }
        return new WorkspaceTreeDTO($$parsedSource as Partial<WorkspaceTreeDTO>);
    }
}

export class WorkspaceTreeNodeDTO {
    "id": string;
    "name": string;
    "path": string;
    "kind": string;
    "size"?: number;
    "children"?: WorkspaceTreeNodeDTO[];
    "truncated"?: boolean;

    /** Creates a new WorkspaceTreeNodeDTO instance. */
    constructor($$source: Partial<WorkspaceTreeNodeDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTreeNodeDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceTreeNodeDTO {
        const $$createField5_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new WorkspaceTreeNodeDTO($$parsedSource as Partial<WorkspaceTreeNodeDTO>);
    }
}

export class WorkspaceTreeWarningDTO {
    "path": string;
    "code": string;

    /** Creates a new WorkspaceTreeWarningDTO instance. */
    constructor($$source: Partial<WorkspaceTreeWarningDTO> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTreeWarningDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceTreeWarningDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceTreeWarningDTO($$parsedSource as Partial<WorkspaceTreeWarningDTO>);
    }
}

export class WorkspaceViewDTO {
    "focus": WorkspaceFocus;
    "artifact"?: ArtifactLocatorV1DTO | null;

    /** Creates a new WorkspaceViewDTO instance. */
    constructor($$source: Partial<WorkspaceViewDTO> = {}) {
        if (!("focus" in $$source)) {
            this["focus"] = WorkspaceFocus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceViewDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceViewDTO {
        const $$createField1_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artifact" in $$parsedSource) {
            $$parsedSource["artifact"] = $$createField1_0($$parsedSource["artifact"]);
        }
        return new WorkspaceViewDTO($$parsedSource as Partial<WorkspaceViewDTO>);
    }
}

export class WorkspaceWarningDTO {
    "code": string;
    "path"?: string;

    /** Creates a new WorkspaceWarningDTO instance. */
    constructor($$source: Partial<WorkspaceWarningDTO> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceWarningDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceWarningDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceWarningDTO($$parsedSource as Partial<WorkspaceWarningDTO>);
    }
}

// Private type creation functions
const $$createType0 = AIProfileDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = DisplayDTO.createFrom;
const $$createType3 = SessionReferenceDTO.createFrom;
const $$createType4 = ProfileSelectionDTO.createFrom;
const $$createType5 = ChatHistoryOptionsDTO.createFrom;
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = CredentialChallengeDTO.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = HistoryMetadataDTO.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = HistoryCitationDTO.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = HistoryUsageDTO.createFrom;
const $$createType14 = HistoryRecordDTO.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ArtifactLocatorV1DTO.createFrom;
const $$createType17 = PreparedLibraryDTO.createFrom;
const $$createType18 = NoteContentDTO.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = WorkspaceSnapshotDTO.createFrom;
const $$createType21 = CapabilityDTO.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Nullable($$createType20);
const $$createType24 = PendingLibraryOperationDTO.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = RecentLibraryDTO.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = $Create.Nullable($$createType16);
const $$createType29 = WorkspaceGraphNodeDTO.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = WorkspaceGraphEdgeDTO.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = WorkspaceSummaryDTO.createFrom;
const $$createType34 = WorkspaceGraphDTO.createFrom;
const $$createType35 = WorkspaceTreeDTO.createFrom;
const $$createType36 = WorkspaceWarningDTO.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = WorkspaceTreeNodeDTO.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = WorkspaceTreeWarningDTO.createFrom;
const $$createType41 = $Create.Array($$createType40);
