// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BuildIndex(request: $models.IndexRequestDTO): $CancellablePromise<$models.IndexStatusDTO> {
    return $Call.ByID(3353806509, request).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CancelChat(reference: $models.SessionReferenceDTO, requestID: string): $CancellablePromise<void> {
    return $Call.ByID(1896547305, reference, requestID);
}

export function CancelIndex(request: $models.IndexRequestDTO): $CancellablePromise<$models.IndexCancelResultDTO> {
    return $Call.ByID(3402286973, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Chat(request: $models.ChatRequestDTO): $CancellablePromise<$models.ChatCompletionDTO> {
    return $Call.ByID(1982707527, request).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ChooseAndActivateWorkspace(): $CancellablePromise<$models.ActivationResult> {
    return $Call.ByID(1183880485).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ClearIndex(request: $models.IndexRequestDTO): $CancellablePromise<$models.IndexStatusDTO> {
    return $Call.ByID(1412208562, request).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ConfirmAndActivateWorkspace(typedRoot: string): $CancellablePromise<$models.ActivationResult> {
    return $Call.ByID(2915745038, typedRoot).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ConfirmSessionCredential(request: $models.ConfirmSessionCredentialRequestDTO): $CancellablePromise<$models.CredentialStatusDTO> {
    return $Call.ByID(285268376, request).then(($result: any) => {
        return $$createType4($result);
    });
}

export function CredentialStatus(request: $models.CredentialReferenceDTO): $CancellablePromise<$models.CredentialStatusDTO> {
    return $Call.ByID(3412347494, request).then(($result: any) => {
        return $$createType4($result);
    });
}

export function DeactivateWorkspace(reference: $models.SessionReferenceDTO): $CancellablePromise<void> {
    return $Call.ByID(2222264444, reference);
}

export function DeleteAIProfile(request: $models.DeleteAIProfileRequestDTO): $CancellablePromise<$models.ProfileDeleteResultDTO> {
    return $Call.ByID(2054984825, request).then(($result: any) => {
        return $$createType5($result);
    });
}

export function DeleteAllHistory(reference: $models.SessionReferenceDTO): $CancellablePromise<$models.HistoryDeleteAllResultDTO> {
    return $Call.ByID(3272496087, reference).then(($result: any) => {
        return $$createType6($result);
    });
}

export function DeleteCredential(request: $models.CredentialReferenceDTO): $CancellablePromise<$models.CredentialDeleteResultDTO> {
    return $Call.ByID(4170438715, request).then(($result: any) => {
        return $$createType7($result);
    });
}

export function DeleteHistory(request: $models.HistoryConversationRequestDTO): $CancellablePromise<$models.HistoryDeleteResultDTO> {
    return $Call.ByID(772358710, request).then(($result: any) => {
        return $$createType8($result);
    });
}

export function EmbeddingConsentStatus(request: $models.EmbeddingConsentRequestDTO): $CancellablePromise<$models.EmbeddingConsentResultDTO> {
    return $Call.ByID(3901646442, request).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GrantEmbeddingConsent(request: $models.EmbeddingConsentRequestDTO): $CancellablePromise<$models.EmbeddingConsentResultDTO> {
    return $Call.ByID(2071612592, request).then(($result: any) => {
        return $$createType9($result);
    });
}

export function HistoryStatus(reference: $models.SessionReferenceDTO): $CancellablePromise<$models.HistoryStatusDTO> {
    return $Call.ByID(4121747709, reference).then(($result: any) => {
        return $$createType10($result);
    });
}

export function IndexStatus(request: $models.IndexRequestDTO): $CancellablePromise<$models.IndexStatusDTO> {
    return $Call.ByID(4273289337, request).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListAIProfiles(): $CancellablePromise<$models.AIProfilesDTO> {
    return $Call.ByID(1057427289).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListHistory(reference: $models.SessionReferenceDTO): $CancellablePromise<$models.HistoryListDTO> {
    return $Call.ByID(180961631, reference).then(($result: any) => {
        return $$createType12($result);
    });
}

export function LoadHistory(request: $models.HistoryConversationRequestDTO): $CancellablePromise<$models.HistoryRecordsDTO> {
    return $Call.ByID(1675013455, request).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ReadCitationNote(request: $models.CitationReadRequestDTO): $CancellablePromise<$models.CitationNoteDTO> {
    return $Call.ByID(4046860084, request).then(($result: any) => {
        return $$createType14($result);
    });
}

export function RevokeEmbeddingConsent(request: $models.EmbeddingConsentRequestDTO): $CancellablePromise<$models.EmbeddingConsentResultDTO> {
    return $Call.ByID(2709511094, request).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SaveAIProfile(request: $models.SaveAIProfileRequestDTO): $CancellablePromise<$models.AIProfileDTO> {
    return $Call.ByID(4173064375, request).then(($result: any) => {
        return $$createType15($result);
    });
}

export function SaveCredential(request: $models.SaveCredentialRequestDTO): $CancellablePromise<$models.CredentialSaveResultDTO> {
    return $Call.ByID(843284269, request).then(($result: any) => {
        return $$createType16($result);
    });
}

export function SetHistoryEnabled(request: $models.SetHistoryEnabledRequestDTO): $CancellablePromise<$models.HistoryStatusDTO> {
    return $Call.ByID(3190712282, request).then(($result: any) => {
        return $$createType10($result);
    });
}

export function WorkspaceTree(reference: $models.SessionReferenceDTO): $CancellablePromise<$models.WorkspaceTreeDTO> {
    return $Call.ByID(3393514150, reference).then(($result: any) => {
        return $$createType17($result);
    });
}

// Private type creation functions
const $$createType0 = $models.IndexStatusDTO.createFrom;
const $$createType1 = $models.IndexCancelResultDTO.createFrom;
const $$createType2 = $models.ChatCompletionDTO.createFrom;
const $$createType3 = $models.ActivationResult.createFrom;
const $$createType4 = $models.CredentialStatusDTO.createFrom;
const $$createType5 = $models.ProfileDeleteResultDTO.createFrom;
const $$createType6 = $models.HistoryDeleteAllResultDTO.createFrom;
const $$createType7 = $models.CredentialDeleteResultDTO.createFrom;
const $$createType8 = $models.HistoryDeleteResultDTO.createFrom;
const $$createType9 = $models.EmbeddingConsentResultDTO.createFrom;
const $$createType10 = $models.HistoryStatusDTO.createFrom;
const $$createType11 = $models.AIProfilesDTO.createFrom;
const $$createType12 = $models.HistoryListDTO.createFrom;
const $$createType13 = $models.HistoryRecordsDTO.createFrom;
const $$createType14 = $models.CitationNoteDTO.createFrom;
const $$createType15 = $models.AIProfileDTO.createFrom;
const $$createType16 = $models.CredentialSaveResultDTO.createFrom;
const $$createType17 = $models.WorkspaceTreeDTO.createFrom;
