// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CheckResult {
    "status": string;
    "summary": CheckSummary;
    "stdout": string;
    "stderr": string;
    "exitCode": number;

    /** Creates a new CheckResult instance. */
    constructor($$source: Partial<CheckResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new CheckSummary());
        }
        if (!("stdout" in $$source)) {
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            this["stderr"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CheckResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField1_0($$parsedSource["summary"]);
        }
        return new CheckResult($$parsedSource as Partial<CheckResult>);
    }
}

export class CheckSummary {
    "errors": number;
    "warnings": number;
    "by_check": { [_ in string]?: number };
    "fixable": number;

    /** Creates a new CheckSummary instance. */
    constructor($$source: Partial<CheckSummary> = {}) {
        if (!("errors" in $$source)) {
            this["errors"] = 0;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = 0;
        }
        if (!("by_check" in $$source)) {
            this["by_check"] = {};
        }
        if (!("fixable" in $$source)) {
            this["fixable"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): CheckSummary {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("by_check" in $$parsedSource) {
            $$parsedSource["by_check"] = $$createField2_0($$parsedSource["by_check"]);
        }
        return new CheckSummary($$parsedSource as Partial<CheckSummary>);
    }
}

// Private type creation functions
const $$createType0 = CheckSummary.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
