// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Edge {
    "from": string;
    "type": string;
    "to": string;

    /** Creates a new Edge instance. */
    constructor($$source: Partial<Edge> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Edge instance from a string or object.
     */
    static createFrom($$source: any = {}): Edge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Edge($$parsedSource as Partial<Edge>);
    }
}

export class Graph {
    "nodes": Node[];
    "edges": Edge[];

    /** Creates a new Graph instance. */
    constructor($$source: Partial<Graph> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Graph instance from a string or object.
     */
    static createFrom($$source: any = {}): Graph {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new Graph($$parsedSource as Partial<Graph>);
    }
}

export class Node {
    "id": string;
    "title": string;
    "type": string;
    "path": string;
    "preview": string;

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("preview" in $$source)) {
            this["preview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Node($$parsedSource as Partial<Node>);
    }
}

// Private type creation functions
const $$createType0 = Node.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Edge.createFrom;
const $$createType3 = $Create.Array($$createType2);
