// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Load(root: string): $CancellablePromise<$models.Graph> {
    return $Call.ByID(397808807, root).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ReadNote(root: string, notePath: string): $CancellablePromise<$models.NoteContent> {
    return $Call.ByID(2818013651, root, notePath).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Graph.createFrom;
const $$createType1 = $models.NoteContent.createFrom;
